---
- name: install the libselinux-python package
  yum: name=libselinux-python state=installed
  tags:
  - common
  - common-misc

- name: disable SELinux in conf file
  selinux: state=disabled
  register: selinux_conf
  tags:
  - common
  - common-misc

- name: disable SELinux in command line
  shell: setenforce 0
  when: selinux_conf|changed
  tags:
  - common
  - common-misc

- name: disable firewalld service
  service: name=firewalld state=stopped enabled=no
  tags:
  - common
  - common-misc
  - common-firewalld
