# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('db_id', models.AutoField(primary_key=True, serialize=False)),
                ('srv_type', models.CharField(max_length=50)),
                ('db_type', models.CharField(max_length=20)),
                ('root_password', models.CharField(max_length=20)),
                ('srv_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('host_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=50)),
                ('srv_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InitServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_list', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('repo_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('host_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=50)),
                ('root_password', models.CharField(max_length=50)),
                ('host_type', models.CharField(default='servers', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('is_db', models.BooleanField(default=False)),
                ('db_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('srv_type', models.CharField(max_length=50)),
                ('host_list', models.CharField(max_length=500)),
                ('host_id', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('task_status', models.CharField(default='NewTask', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
