---
- name: install ambari-server package
  yum: name=ambari-server state=present
  tags:
  - ambari-server
  - ambari-server-rpm

- name: run ambari setup command
  shell: /usr/sbin/ambari-server setup -j /usr/java/default  -s
  tags:
  - ambari-server
  - ambari-server-init

- name: start ambari-server service
  service: name=ambari-server enabled=yes state=started
  tags:
  - ambari-server
  - ambari-server-service
